import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import AOSInitializer from '@/components/OASInitializer';
import 'aos/dist/aos.css';
import Loader from "@/components/ui/Loader";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "IELTS Sprint",
  description: "Generated by create next app",
  icons: "/assets/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js">
      <head>
        
      </head>
      <body className={`${montserrat.variable} ${roboto.variable}`}>
        <AOSInitializer>
                  {children}
        </AOSInitializer>
        {/* <Loader></Loader> */}
      </body>
    </html>
  );
}
